short_prompts = [
    "Write a detailed, chapter-by-chapter outline for a 12-chapter fantasy novel, then write the full first chapter (at least 2000 words) with dialogue, scene description, and character introductions.",

    "Explain how a modern CPU works from the ground up: transistors, logic gates, the ALU, registers, cache hierarchy, the fetch-decode-execute cycle, pipelining, branch prediction, and out-of-order execution. Give concrete examples for each section and don't skip steps.",

    "Write a complete, heavily commented Python implementation of a small interpreter for a toy programming language, including the lexer, parser (recursive descent), AST node classes, and a tree-walking evaluator. After the code, walk through how each component works line by line.",

    "Provide a comprehensive history of the Roman Empire from its founding through its fall, broken into major eras. For each era, cover the key emperors, political developments, military campaigns, economic conditions, and cultural shifts. Include specific dates and explain causes and consequences throughout.",

    "Create a 7-day detailed travel itinerary for Japan covering Tokyo, Kyoto, and Osaka. For each day, give a morning/afternoon/evening breakdown with specific attractions, restaurant suggestions, transit directions, estimated costs, and practical tips.",
]



# Each prompt is designed to be approximately 512 input tokens (~380 words at
# ~1.35 tokens/word for dense technical English), matching the available input
# budget of max_model_len(768) - output_len(256) = 512 tokens.
prompts = [
    # 1 – Machine Learning: Backpropagation  (~374 words ≈ 505 tokens)
    ("You are a senior machine learning researcher. Provide a detailed, graduate-level technical "
     "explanation of how backpropagation works inside a deep neural network, written for a software "
     "engineer who knows calculus and linear algebra. Structure your response as follows. First, define "
     "neural networks in terms of layered linear transformations and non-linear activation functions "
     "such as ReLU, sigmoid, tanh, and GELU, explaining what each activation contributes and why "
     "non-linearity is essential for learning complex functions. Define the loss function precisely, "
     "giving examples of mean squared error for regression and categorical cross-entropy for "
     "classification, and explain geometrically what minimizing the loss means in high-dimensional "
     "parameter space. Second, introduce gradient descent as the core optimization strategy: explain "
     "the intuition of moving in the direction of the negative gradient, the role of the learning rate, "
     "and why vanilla gradient descent is impractical on large datasets, motivating stochastic and "
     "mini-batch variants. Third, carefully derive the chain rule of calculus and demonstrate "
     "step-by-step how it applies during the backward pass through multiple stacked layers. For each "
     "layer write the explicit partial derivative expressions for the weight gradient and the gradient "
     "that flows backward to the prior layer, clearly tracking matrix dimensions throughout. Fourth, "
     "explain how computed gradients are used by optimizers: cover SGD with momentum, AdaGrad, RMSProp, "
     "and Adam, presenting update equations for each and explaining the intuition behind adaptive "
     "per-parameter learning rates. Fifth, address the vanishing and exploding gradient problems: "
     "derive mathematically why they emerge in deep networks, describe observable training symptoms, "
     "and explain every standard remedy including gradient clipping, Xavier and He initialization, "
     "batch normalization with its forward normalization step and backward gradient computation, "
     "layer normalization, and residual skip connections as used in ResNet and Transformer architectures. "
     "Sixth, work through a complete numerical example using a two-layer fully connected network: "
     "show every step of the forward pass with concrete numbers, compute the loss, execute the full "
     "backward pass showing exact gradient values at every weight and bias, and apply an SGD update. "
     "Finally, explain how PyTorch implements reverse-mode automatic differentiation through dynamic "
     "computational graphs, and why this makes building novel architectures significantly easier "
     "than writing backpropagation by hand."),

    # 2 – Quantum Computing: Fundamentals  (~368 words ≈ 497 tokens)
    ("You are a quantum computing expert with backgrounds in both physics and computer science. "
     "Provide a comprehensive explanation of how quantum computers work, targeted at experienced "
     "software engineers with strong mathematical backgrounds but minimal quantum mechanics exposure. "
     "Begin by carefully distinguishing a classical bit from a qubit: define superposition using "
     "Dirac bra-ket notation, explain the Bloch sphere representation, and correct the common "
     "misconception that superposition simply means the qubit is simultaneously zero and one. "
     "Introduce quantum state as a unit vector in a complex Hilbert space, explain Born's rule so "
     "that measurement probabilities equal the squared moduli of amplitudes, and state the "
     "no-cloning theorem and explain why it prevents copying an unknown quantum state. "
     "Explain quantum entanglement mathematically: show what it means for a two-qubit state to be "
     "non-separable, give the four Bell states as examples, and clarify why correlated measurement "
     "outcomes do not enable faster-than-light communication. Introduce quantum gates as unitary "
     "matrices: describe the Pauli X, Y, and Z gates, the Hadamard gate, the phase gate, and the "
     "CNOT gate, and show how a circuit of gates corresponds to a sequence of matrix multiplications. "
     "Explain quantum interference: describe how algorithms structure circuits so that amplitudes "
     "for wrong answers cancel while amplitudes for correct answers reinforce, using "
     "Deutsch's algorithm as a minimal concrete example. Explain quantum speedup: describe the "
     "complexity class BQP and its believed relationship to P and NP, cover Shor's algorithm for "
     "prime factorization explaining why it breaks RSA via the quantum Fourier transform, and cover "
     "Grover's algorithm for unstructured search explaining why its quadratic speedup is optimal. "
     "Discuss the physical challenges of building quantum computers: explain decoherence and how "
     "environmental noise destroys superposition, describe gate fidelity requirements, explain the "
     "quantum error correction threshold theorem, and survey superconducting qubits as used by IBM "
     "and Google, trapped-ion qubits as used by IonQ and Quantinuum, and neutral-atom platforms. "
     "Conclude with a realistic assessment of where genuine quantum advantage has been demonstrated "
     "versus merely claimed, and identify the most promising near-term applications in optimization, "
     "quantum chemistry simulation, and machine learning."),

    # 3 – Operating Systems: Process and Thread Management  (~357 words ≈ 482 tokens)
    ("You are an expert operating systems engineer and educator. Write a thorough, technically precise "
     "explanation of how modern operating systems manage processes and threads, targeted at a programmer "
     "who has used operating systems for years but never studied them formally. Begin with the definition "
     "of a process: explain what a process is in terms of its memory layout including the text segment, "
     "data segment, heap, and stack, describe what the operating system stores in the process control "
     "block, and explain how the OS maintains the table of all running processes. Distinguish a process "
     "from a thread: explain threads as independently schedulable units of execution that share the "
     "address space and file descriptors of their parent process, and describe what per-thread state the "
     "OS must maintain including the thread stack and register file. Explain context switching: describe "
     "exactly what the CPU and OS do when preempting a running process, including saving all CPU "
     "registers, the program counter, and the stack pointer to the PCB, selecting the next process via "
     "the scheduler, restoring saved state, and returning to user mode. Explain the main CPU scheduling "
     "algorithms: first-come first-served, shortest job next, round-robin, multilevel feedback queues, "
     "and the Completely Fair Scheduler used in Linux, covering the trade-offs each makes between "
     "throughput, latency, and fairness. Explain process creation using fork and exec on UNIX: describe "
     "what fork does to the address space using copy-on-write, what exec does to replace the process "
     "image, and how parent and child processes relate to the init process. Cover inter-process "
     "communication mechanisms: pipes, named pipes, shared memory, message queues, and sockets, "
     "explaining the data model and typical use case of each. Explain synchronization primitives: "
     "mutex locks, semaphores, condition variables, and read-write locks, and describe the classical "
     "producer-consumer, readers-writers, and dining philosophers problems. Describe deadlock: state "
     "the four Coffman conditions, explain detection, prevention, and avoidance strategies including "
     "the Banker's algorithm, and discuss how real operating systems handle deadlock in practice."),

    # 4 – Databases: Query Optimization  (~362 words ≈ 489 tokens)
    ("You are a database expert with deep knowledge of relational database internals. Explain in "
     "technical detail how a relational DBMS processes and optimizes SQL queries, aimed at a developer "
     "who writes SQL daily but has never studied database internals. Begin with the query processing "
     "pipeline: describe how the DBMS passes a SQL string through lexing, parsing to produce a parse "
     "tree, semantic analysis to verify table and column names against the catalog, logical plan "
     "generation to produce a relational algebra expression, and physical plan generation where the "
     "optimizer chooses algorithms for each operator. Explain the relational algebra operators that "
     "form logical plans: selection, projection, join, aggregation, sort, and distinct, and show how "
     "SQL maps to sequences of these operators. Describe the role of the system catalog: explain that "
     "it stores table cardinalities, column histograms, index metadata, and column correlations, and "
     "explain how the optimizer uses these statistics to estimate intermediate result sizes. Explain "
     "predicate pushdown as a rule-based rewriting optimization: show how moving filters close to base "
     "tables reduces row counts flowing through upstream operators. Explain the physical algorithms for "
     "joins: nested-loop join, block nested-loop join, hash join, and sort-merge join, covering "
     "algorithmic steps, time and space complexity in buffer pages, and the circumstances under which "
     "each is preferred. Cover index types: explain B-tree indexes supporting equality and range scans, "
     "hash indexes for equality-only workloads, and covering indexes enabling index-only scans. "
     "Describe cost-based optimization: explain how the optimizer enumerates join orderings using "
     "dynamic programming to find the minimum-cost plan, and explain why join ordering is exponentially "
     "expensive in the number of tables. Explain execution engine approaches: interpreted versus "
     "compiled execution, vectorized execution as used in columnar databases like DuckDB and Snowflake, "
     "and how SIMD instructions accelerate batch processing of column arrays. Conclude by explaining "
     "how to read a query execution plan produced by EXPLAIN ANALYZE in PostgreSQL, including how to "
     "identify sequential scans that should be replaced with index scans and join algorithms that are "
     "suboptimal for the given data distribution."),

    # 5 – Cryptography: Public Key Infrastructure and TLS  (~365 words ≈ 493 tokens)
    ("You are a cryptography and network security expert. Explain the fundamentals of public key "
     "cryptography and how TLS 1.3 secures web connections, targeted at a developer who uses HTTPS "
     "every day but has never studied how it works beneath the surface. Begin with symmetric "
     "cryptography: explain shared secret keys, describe block ciphers versus stream ciphers, and "
     "explain AES in terms of its substitution-permutation network structure, key schedule, and why "
     "256-bit keys are considered secure against brute force. Explain the key distribution problem: "
     "describe why two parties who have never met cannot use symmetric cryptography without a way to "
     "establish a shared key, and explain why this was unsolved for decades. Introduce Diffie-Hellman "
     "key exchange: describe the discrete logarithm problem, walk through the protocol showing how "
     "Alice and Bob each contribute entropy to the shared secret without ever transmitting it, and "
     "explain why an eavesdropper who sees all messages cannot reconstruct the secret. Explain RSA: "
     "describe the mathematical foundation in modular exponentiation and integer factorization hardness, "
     "walk through key generation including selecting primes p and q, computing n and phi of n, "
     "choosing e, and computing d as the modular inverse of e, then explain encryption and decryption. "
     "Explain digital signatures: describe how a sender signs using the private key and a recipient "
     "verifies using the public key, and explain why this provides authentication and non-repudiation. "
     "Introduce X.509 certificates: explain what a certificate contains including subject, issuer, "
     "public key, validity dates, and the certificate authority signature, and explain the chain of "
     "trust from root CA through intermediate CAs to a leaf certificate. Describe the TLS 1.3 "
     "handshake in detail: cover client hello, server hello, Elliptic Curve Diffie-Hellman Ephemeral "
     "key exchange, server certificate verification, the Finished messages, and session key derivation "
     "using HKDF. Explain forward secrecy and why ECDHE provides it while static RSA key exchange "
     "does not. Conclude by explaining common attacks and defenses: MITM attacks, certificate pinning, "
     "OCSP stapling, and certificate transparency logs."),

    # 6 – Distributed Systems: Raft Consensus  (~372 words ≈ 502 tokens)
    ("You are a distributed systems expert. Provide a thorough technical explanation of the Raft "
     "consensus algorithm, written for a senior software engineer who understands single-machine "
     "concurrency but has limited distributed systems experience. Begin by motivating the consensus "
     "problem precisely: define what consensus means in a cluster of servers, state the safety and "
     "liveness properties any correct algorithm must satisfy, and describe the crash-stop failure model, "
     "distinguishing it from Byzantine failures and explaining why most production systems only need "
     "to tolerate crash-stop faults. Describe Paxos briefly to establish historical context: cover the "
     "roles of proposers, acceptors, and learners, walk through the two-phase prepare-and-accept "
     "protocol, explain correctness via the quorum intersection argument, and describe why Paxos is "
     "famously difficult to implement fully in production systems. Introduce Raft as a more "
     "understandable alternative designed around strong leadership. Explain leader election in detail: "
     "describe the three server states of follower, candidate, and leader, explain how election "
     "timeouts trigger candidacy, describe the RequestVote RPC including the term number and log "
     "completeness checks, and explain how a new leader is elected by majority vote while preventing "
     "split votes using randomized election timeouts. Explain Raft log replication: describe how the "
     "leader appends entries to its log and sends AppendEntries RPCs to followers, explain the commit "
     "criterion requiring acknowledgment from a majority of servers, and explain how the leader "
     "advances the commit index and how followers apply committed entries to their state machines. "
     "Cover the Raft safety argument: explain the leader completeness property ensuring all committed "
     "entries appear in the logs of future leaders, and explain the log matching property ensuring "
     "replicas never diverge. Explain leader changes and log reconciliation: describe how a new leader "
     "forces followers whose logs diverge to overwrite their conflicting entries. Cover joint consensus "
     "for cluster membership changes and log compaction using snapshots. Conclude with a practical "
     "discussion of Raft performance including the role of batching and pipelining in achieving high "
     "throughput, and describe how Raft is used in production systems such as etcd, CockroachDB, "
     "and TiKV."),

    # 7 – Compilers: Source to Machine Code  (~362 words ≈ 489 tokens)
    ("You are a compiler engineer with experience building production language toolchains. Explain in "
     "technical detail how a compiler works from source code to machine code, written for an experienced "
     "developer who has never built a compiler but is curious about what happens under the hood when "
     "they run gcc or javac. Organize your explanation into the major compiler phases. First, explain "
     "lexical analysis: describe the lexer's role in scanning source text and producing a token stream, "
     "explain what a token is as a categorized piece of source text such as an identifier, keyword, "
     "integer literal, or operator, and describe how finite automata and regular expressions recognize "
     "tokens efficiently. Second, explain parsing: describe how the parser consumes tokens and builds "
     "an abstract syntax tree representing the grammatical structure of the program. Explain "
     "context-free grammars and the difference between terminals and non-terminals. Describe "
     "top-down recursive-descent parsing in detail: explain how each grammar rule maps to a parsing "
     "function, how FIRST and FOLLOW sets guide lookahead, and how the parser recursively builds AST "
     "nodes. Also mention bottom-up LR parsing and the shift-reduce mechanism. Third, explain semantic "
     "analysis: describe the symbol table, type checking, scope resolution, and how the compiler "
     "detects errors such as undeclared variables, type mismatches, and unreachable code. Fourth, "
     "explain intermediate representation: describe three-address code, static single assignment form "
     "and why it simplifies analysis, and LLVM IR as a widely used real-world IR. Fifth, cover key "
     "optimizations: constant folding, dead code elimination, common subexpression elimination, loop "
     "invariant code motion, function inlining, and alias analysis, explaining intuitively why each "
     "is correct and what class of programs it benefits. Sixth, explain code generation: describe "
     "instruction selection using tree-pattern matching, register allocation using graph coloring, "
     "and instruction scheduling to exploit instruction-level parallelism. Explain the difference "
     "between ahead-of-time and just-in-time compilation, and describe how JIT compilers profile "
     "runtime behavior to make better optimization decisions. Conclude by explaining how DWARF "
     "debugging information is emitted alongside machine code to allow debuggers to map binary "
     "instructions back to source lines."),

    # 8 – Networking: TCP/IP Protocol Stack  (~362 words ≈ 489 tokens)
    ("You are a networking expert with experience in both theory and production systems. Explain in "
     "thorough technical detail how the TCP/IP protocol stack works, written for a developer who uses "
     "sockets and HTTP daily but has never studied networking formally. Organize your explanation by "
     "layer. Begin with the data link layer: explain Ethernet frames including MAC source and "
     "destination addresses, the EtherType field, payload, and frame check sequence, and explain how "
     "switches learn MAC addresses and build forwarding tables to avoid broadcasting every frame. "
     "Explain the Internet Protocol layer: describe the IPv4 packet header fields including version, "
     "header length, differentiated services, total length, identification, flags, fragment offset, "
     "TTL, protocol, checksum, and source and destination addresses. Explain CIDR and subnet masks. "
     "Describe how routers use longest-prefix-match in routing tables to forward packets hop by hop. "
     "Explain ARP and how a host discovers the MAC address for a given IP on the local network. "
     "Explain the transport layer: describe UDP as a connectionless protocol providing only "
     "best-effort delivery, and explain scenarios where UDP is preferable such as DNS, video "
     "streaming, and online games. Then explain TCP in detail: describe the three-way handshake for "
     "connection establishment, the four-way handshake for teardown, and the full TCP state machine. "
     "Explain reliable delivery via sequence numbers, acknowledgment numbers, retransmission timers, "
     "and cumulative acknowledgments. Explain flow control using the receiver window: describe how "
     "the receiver advertises available buffer space and how the sender limits in-flight data. "
     "Explain TCP congestion control in detail: cover slow start, congestion avoidance, fast retransmit "
     "and fast recovery, and the CUBIC algorithm used in Linux. Describe the application layer: explain "
     "how HTTP/1.1 uses persistent connections with head-of-line blocking, how HTTP/2 introduces "
     "multiplexed streams over a single TCP connection with header compression, and how HTTP/3 "
     "replaces TCP with QUIC to eliminate transport-layer head-of-line blocking entirely. Explain "
     "how TLS slots between TCP and HTTP to provide encryption, authentication, and integrity "
     "using the handshake and record protocol you described earlier."),

    # 9 – History: The French Revolution  (~382 words ≈ 516 tokens)
    ("You are a historian specializing in early modern European history. Provide a comprehensive and "
     "analytically rich account of the French Revolution from its origins in the 1780s through the "
     "rise of Napoleon Bonaparte. Go beyond a chronicle of events and explain causes, social dynamics, "
     "ideological conflicts, and long-term consequences. Begin with the deep structural causes: analyze "
     "the fiscal crisis of the French state, the burden of debt from the Seven Years War and the "
     "American Revolutionary War, the inability of the crown to reform its tax base due to noble and "
     "clerical exemptions, and the resulting bankruptcy that forced Louis XVI to convene the "
     "Estates-General for the first time since 1614. Explain the social tensions: describe the three "
     "estates, the grievances of the bourgeoisie and peasantry, the Enlightenment ideas of natural "
     "rights and popular sovereignty spreading through pamphlets and salons, and how the harvest "
     "failures and bread shortages of 1788 to 1789 transformed abstract political discontent into "
     "popular fury. Describe the political rupture of 1789: explain the transformation of the "
     "Estates-General into the National Assembly, the Tennis Court Oath, the fall of the Bastille and "
     "its symbolic importance, the Great Fear in the countryside, and the August Decrees abolishing "
     "feudalism. Trace the constitutional monarchy period from 1789 to 1792: cover the Declaration "
     "of the Rights of Man and of the Citizen, the October Days, the Civil Constitution of the Clergy, "
     "the Flight to Varennes, and the growing polarization between constitutional monarchists and "
     "republicans. Describe the radical phase from 1792 to 1794: explain the declaration of the "
     "Republic, the trial and execution of Louis XVI, the formation of the Committee of Public Safety, "
     "the Reign of Terror under Robespierre, the logic of revolutionary tribunals, and the "
     "Thermidorian Reaction that ended the Terror. Describe the Directory from 1795 to 1799 and its "
     "institutional instability. Explain Napoleon's coup of 18 Brumaire and analyze the historiographic "
     "debate about whether the Revolution was consolidated or betrayed by Napoleonic rule. Conclude "
     "with the long-term legacy of the Revolution for European politics, nationalism, liberalism, "
     "and the spread of democratic ideals throughout the nineteenth century."),

    # 10 – Biology: CRISPR-Cas9 Gene Editing  (~378 words ≈ 510 tokens)
    ("You are a molecular biologist and bioethicist. Provide a thorough explanation of CRISPR-Cas9 "
     "gene editing technology, written for an educated non-specialist who understands basic biology "
     "but has no molecular biology background. Cover both the science and the ethical dimensions. "
     "Begin with the molecular machinery: explain what CRISPR stands for and how the natural "
     "CRISPR-Cas9 system functions as an adaptive immune mechanism in bacteria, allowing them to "
     "recognize and cut the DNA of invading bacteriophages by storing short fragments of viral DNA "
     "in their own genome. Describe how Doudna and Charpentier adapted this system into a "
     "programmable gene editing tool, earning the 2020 Nobel Prize in Chemistry. Explain the two "
     "components: the Cas9 protein acting as molecular scissors that cuts double-stranded DNA, and "
     "the single guide RNA, a short synthetic molecule that hybridizes to a target DNA sequence and "
     "directs Cas9 to cut at precisely that location. Explain the protospacer adjacent motif "
     "requirement and why it constrains but does not severely limit targeting options. Describe the "
     "two major DNA repair pathways determining editing outcomes: non-homologous end joining, which "
     "is error-prone and typically produces small insertions or deletions that disrupt gene function, "
     "and homology-directed repair, which can introduce precise sequence changes using a provided "
     "template but is less efficient. Explain off-target effects: describe how Cas9 occasionally cuts "
     "at partially matching sites, the genome-wide detection methods such as GUIDE-seq, and improved "
     "high-fidelity Cas9 variants developed to reduce off-target activity. Survey therapeutic "
     "applications: describe the FDA-approved treatments for sickle cell disease and beta-thalassemia, "
     "ongoing clinical trials for cancer immunotherapy, hereditary blindness, and high cholesterol, "
     "and explain the distinction between somatic cell editing affecting only the patient versus "
     "germline editing affecting all descendant cells. Discuss ethics of germline editing: explain "
     "the case of He Jiankui who edited human embryos in 2018, the global scientific and ethical "
     "objections raised by the research community, the international governance frameworks being "
     "developed, and the ongoing debate about the line between treating disease and enhancing traits."),

    # 11 – Physics: General Relativity  (~376 words ≈ 508 tokens)
    ("You are a theoretical physicist and science educator. Explain Einstein's theory of general "
     "relativity to a reader with solid classical physics and some special relativity knowledge, but "
     "no exposure to differential geometry or tensor calculus. Build genuine physical intuition while "
     "providing enough mathematical grounding that the reader could continue to a rigorous treatment. "
     "Begin with the equivalence principle: explain both the weak form equating gravitational and "
     "inertial mass and the strong form equating physics in a freely falling frame to physics in flat "
     "spacetime. Describe Einstein's elevator thought experiments and explain how they led to the "
     "insight that gravity is not a Newtonian force but a manifestation of spacetime curvature. "
     "Introduce the concept of spacetime: explain how special relativity unifies space and time into "
     "a four-dimensional continuum where the spacetime interval is invariant under Lorentz "
     "transformations. Explain what spacetime curvature means: introduce manifolds and the metric "
     "tensor informally, explain geodesics as the straightest paths through curved spacetime, and "
     "describe how freely falling objects follow geodesics rather than being deflected by a force. "
     "Present the Einstein field equations qualitatively: explain that they relate the Einstein tensor "
     "encoding spacetime curvature to the stress-energy tensor encoding the distribution of mass, "
     "energy, and momentum, conveying the physical meaning as mass-energy telling spacetime how to "
     "curve while curved spacetime tells matter how to move. Discuss experimental confirmations: "
     "describe the precession of Mercury's perihelion, gravitational lensing including the 1919 "
     "Eddington expedition, gravitational time dilation and its practical importance for GPS satellite "
     "accuracy, and gravitational waves and the 2015 LIGO detection. Cover the Schwarzschild solution: "
     "explain what a black hole is, define the Schwarzschild radius and the event horizon, describe "
     "the behavior of light and infalling matter near a black hole, and explain the information paradox "
     "briefly. Conclude by describing open fundamental questions including the incompatibility of "
     "general relativity with quantum mechanics, the cosmological constant and dark energy, the "
     "hierarchy problem, and the ongoing search for a consistent theory of quantum gravity through "
     "approaches such as string theory and loop quantum gravity."),

    # 12 – Economics: Game Theory and Nash Equilibrium  (~378 words ≈ 510 tokens)
    ("You are an economist and game theorist. Provide a thorough, technically precise explanation of "
     "game theory and Nash equilibrium, written for a developer or data scientist who is "
     "mathematically comfortable but has never formally studied economics or game theory. Begin by "
     "defining a game in the formal sense: a set of players, each with a set of available strategies, "
     "and a payoff function assigning numerical utility to each player for every combination of "
     "strategy choices. Explain the difference between cooperative and non-cooperative game theory, "
     "clarifying that this explanation focuses on non-cooperative games. Explain normal form and "
     "extensive form representations: describe the payoff matrix for a two-player finite game and "
     "game trees for sequential games including information sets capturing what each player knows "
     "when deciding. Define dominant strategies: explain strict and weak dominance, describe iterative "
     "elimination of dominated strategies, and show why this process sometimes uniquely solves a game "
     "and sometimes leaves multiple equilibria. Define Nash equilibrium precisely as a strategy "
     "profile where no player can improve their payoff by unilaterally deviating, distinguish pure "
     "strategy Nash equilibria from mixed strategy Nash equilibria, and state Nash's existence theorem "
     "guaranteeing at least one equilibrium in mixed strategies for every finite game. Work through "
     "canonical examples carefully: analyze the Prisoner's Dilemma showing why mutual defection is "
     "the unique Nash equilibrium despite mutual cooperation giving higher payoffs, explain the Stag "
     "Hunt and the coordination problem, analyze the Battle of the Sexes with multiple equilibria, "
     "and explain the Hawk-Dove game and its mixed strategy equilibrium. Cover Pareto efficiency: "
     "define Pareto-optimal outcomes and explain why Nash equilibria are often Pareto-inefficient "
     "using the Prisoner's Dilemma as the canonical example. Introduce repeated games and the Folk "
     "Theorem: explain how indefinitely repeated interaction sustains cooperation as a subgame perfect "
     "equilibrium when players are sufficiently patient. Survey applications in auction theory, "
     "mechanism design, and algorithmic game theory including congestion games and the price of "
     "anarchy. Conclude by discussing limitations and criticisms of Nash equilibrium as a solution "
     "concept: coordination problems among multiple equilibria, rationality and common knowledge "
     "assumptions, and evolutionary game theory as an alternative foundation."),

    # 13 – Philosophy: The Hard Problem of Consciousness  (~381 words ≈ 514 tokens)
    ("You are a philosopher of mind with expertise in both analytic philosophy and cognitive science. "
     "Provide a thorough philosophical examination of the hard problem of consciousness and the major "
     "philosophical positions regarding the nature of mind, written for an educated reader who has "
     "not studied philosophy formally but thinks carefully about these questions. Begin by "
     "distinguishing the easy problems of consciousness from the hard problem as articulated by David "
     "Chalmers: explain that the easy problems involve explaining cognitive and behavioral functions "
     "such as attention, memory, introspection, and information integration, while the hard problem "
     "is explaining why there is subjective experience at all, why there is something it is like to "
     "be a conscious creature seeing red or feeling pain. Introduce qualia as the intrinsic subjective "
     "character of experience and explain why their existence poses a special explanatory challenge. "
     "Survey physicalist positions: describe eliminative materialism and Churchland's argument that "
     "folk psychological concepts will be replaced by neuroscience, describe reductive functionalism "
     "and the claim that mental states are defined by causal roles and can be multiply realized in "
     "different physical substrates, and describe identity theory claiming mental states are literally "
     "identical to brain states. Explain the major objections to physicalism: present Nagel's bat "
     "argument that subjective experience cannot be captured by objective physical description, "
     "present Jackson's knowledge argument with Mary the color scientist who knows all physical facts "
     "about color vision but learns something new upon first seeing red, and present Chalmers' "
     "philosophical zombie conceivability argument. Survey non-physicalist positions: describe "
     "property dualism holding that phenomenal properties are fundamental and irreducible to physical "
     "properties, describe panpsychism holding that proto-conscious properties are fundamental "
     "features of the world, and explain integrated information theory as a scientific framework with "
     "panpsychist implications. Describe the global workspace theory as a leading neuroscientific "
     "account of consciousness. Explain the binding problem: describe how the brain integrates "
     "information processed in separate regions into a unified conscious experience. Conclude by "
     "discussing whether the hard problem is genuinely insoluble and what advances in neuroscience, "
     "large language models, and artificial general intelligence might reveal about the nature of "
     "mind and consciousness."),

    # 14 – Chemistry: Lithium-Ion Batteries and Electrochemistry  (~376 words ≈ 508 tokens)
    ("You are an electrochemist and battery technology expert. Provide a thorough technical "
     "explanation of how electrochemical batteries work, from fundamental physics and chemistry "
     "through modern lithium-ion cells and emerging technologies, written for an engineer with a "
     "solid chemistry background but no electrochemistry specialization. Begin with the fundamentals: "
     "define oxidation and reduction precisely, explain conventions for writing half-reactions, and "
     "describe how a galvanic cell converts a spontaneous chemical reaction into electrical energy by "
     "separating the oxidation and reduction half-reactions at different electrodes. Explain standard "
     "reduction potentials: describe the electrochemical series, explain how to calculate cell voltage "
     "from cathode and anode reduction potentials, and explain the thermodynamic relationship between "
     "cell voltage and the Gibbs free energy change of the overall reaction. Describe the Nernst "
     "equation and explain how cell voltage depends on reactant and product concentrations under "
     "non-standard conditions. Explain the internal structure of a galvanic cell: describe the anode, "
     "cathode, electrolyte as an ionic conductor, and the role of the separator in preventing short "
     "circuits while allowing ion transport. Explain the concept of overpotential: describe activation "
     "overpotential from slow electrode kinetics, concentration overpotential from mass transport "
     "limitations near the electrode surface, and ohmic overpotential from electrolyte resistance. "
     "Cover lead-acid batteries as a classical example: describe electrode reactions during discharge "
     "and charging, explain why they deliver high currents, and describe their key limitations. "
     "Explain lithium-ion batteries in detail: describe the intercalation mechanism by which lithium "
     "ions are inserted into and extracted from electrode materials during cycling, describe common "
     "cathode materials including lithium cobalt oxide, lithium iron phosphate, and NMC chemistries "
     "with their tradeoffs in energy density, cycle life, cost, and safety, describe graphite anodes "
     "and silicon anode development, and explain the formation and function of the solid electrolyte "
     "interphase layer. Discuss thermal runaway, its causes, and the battery management systems used "
     "to prevent it. Survey emerging technologies: solid-state batteries replacing liquid electrolyte, "
     "lithium-sulfur batteries offering higher theoretical energy density, sodium-ion batteries as "
     "a lower-cost alternative, and redox flow batteries for grid-scale stationary storage."),

    # 15 – Mathematics: Eigendecomposition and SVD  (~376 words ≈ 508 tokens)
    ("You are a mathematician and data scientist. Provide a thorough, technically precise explanation "
     "of eigenvalues, eigenvectors, and matrix decompositions, written for a programmer who has used "
     "linear algebra in code but never studied it formally at a graduate level. The goal is genuine "
     "mathematical understanding rather than formula familiarity. Begin with a geometric "
     "interpretation of matrix-vector multiplication: explain that every matrix represents a linear "
     "transformation of space, describe what the determinant measures geometrically as signed volume "
     "scaling, and explain what it means for a transformation to stretch, rotate, reflect, or shear "
     "space. Define eigenvalues and eigenvectors precisely: explain that an eigenvector is a non-zero "
     "vector the transformation scales without changing direction, and the eigenvalue is the scalar "
     "scaling factor. Derive the characteristic polynomial: show that the eigenvalue equation "
     "A times v equals lambda times v can be rewritten as det of A minus lambda I equals zero, and "
     "explain how the roots of this polynomial give the eigenvalues. Explain how to find eigenvectors "
     "once eigenvalues are known by solving the corresponding homogeneous linear system, and explain "
     "the concepts of eigenspace, algebraic multiplicity, and geometric multiplicity. Explain the "
     "spectral theorem: state that every real symmetric matrix is orthogonally diagonalizable with "
     "real eigenvalues, explain what this means geometrically as the matrix representing pure scaling "
     "along orthogonal axes, and explain why this is a powerful structural result for applications. "
     "Explain eigendecomposition: describe writing a diagonalizable matrix as P times D times the "
     "inverse of P, where P contains eigenvectors as columns and D is the diagonal eigenvalue matrix. "
     "Introduce the singular value decomposition: explain that SVD decomposes any matrix as U times "
     "Sigma times V-transpose where U and V have orthonormal columns and Sigma is diagonal with "
     "non-negative singular values, explain the geometric interpretation as a rotation-scaling-rotation "
     "composition, and explain why SVD exists for every matrix while eigendecomposition requires "
     "diagonalizability. Describe major applications: principal component analysis for dimensionality "
     "reduction, least-squares regression via the Moore-Penrose pseudoinverse, spectral graph theory "
     "and graph Laplacians, the PageRank algorithm, and low-rank matrix approximation for "
     "recommendation systems, image compression, and natural language processing embeddings."),

    # 16 – Statistics: Bayesian Inference and MCMC  (~381 words ≈ 514 tokens)
    ("You are a statistician and machine learning researcher. Explain Bayesian inference and Markov "
     "Chain Monte Carlo sampling methods in technical detail, written for a data scientist comfortable "
     "with frequentist statistics and basic probability but who has never studied Bayesian methods "
     "formally. Begin by clearly distinguishing frequentist and Bayesian interpretations of "
     "probability: explain the frequentist view as a limiting frequency of events in repeated "
     "experiments, and the Bayesian view as a degree of rational belief quantifying uncertainty about "
     "propositions. Explain Bayes' theorem precisely in the context of statistical inference: identify "
     "the prior distribution encoding beliefs before observing data, the likelihood as the probability "
     "of observed data given parameters, the posterior distribution as updated beliefs after observing "
     "data, and the marginal likelihood as the normalizing constant. Explain why the marginal "
     "likelihood is usually intractable to compute analytically for complex models, as it requires "
     "integrating over the entire parameter space, and how this makes exact Bayesian inference "
     "difficult in most real-world problems. Describe conjugate prior families as a special case where "
     "the posterior has the same distributional form as the prior: cover the beta-binomial, "
     "Dirichlet-multinomial, and normal-normal conjugate pairs, explain their algebraic convenience, "
     "and explain why conjugacy is rarely available for complex hierarchical models. Introduce Markov "
     "Chain Monte Carlo as the general solution to posterior inference: explain that MCMC constructs "
     "a Markov chain whose stationary distribution equals the target posterior, so that samples from "
     "the chain after a burn-in period are approximate samples from the posterior. Explain the "
     "Metropolis-Hastings algorithm in detail: describe the proposal distribution, the acceptance "
     "ratio including both the likelihood ratio and prior ratio terms, the accept-reject step, and "
     "prove intuitively why the algorithm achieves the correct stationary distribution through "
     "detailed balance. Explain the Gibbs sampler: describe sampling each variable from its full "
     "conditional distribution in turn, explain computational convenience when full conditionals are "
     "closed-form, and describe the potential for slow mixing when variables are strongly correlated. "
     "Describe Hamiltonian Monte Carlo and the No-U-Turn Sampler used in Stan and PyMC: explain how "
     "HMC uses gradient information to make large efficient proposals in high-dimensional spaces, "
     "dramatically reducing autocorrelation compared to random-walk Metropolis, and describe "
     "convergence diagnostics including R-hat and effective sample size."),
]
